### ISSUE TITLE
Label "Deposit" in FunctionCall proposal as NEAR

### ISSUE THREAD

**Issue by Tarnadas** [near-ndc/AstraPlusPlus#30]
When creating a FunctionCall proposal it is very confusing, that Gas should be given in Gas (instead of e.g. TGas), but Deposit right below should be given in NEAR instead of yoctoNEAR. These need to be labeled properly.

It's also kind of annoying to insert 0.000000000000000000000001, if you need to attach 1 yoctoNEAR for e.g. `ft_transfer_call`.

**Comment by Megha-Dev-19** [comment]
Resolved by #55
