### ISSUE TITLE
No Way to Change Quorum

### ISSUE THREAD

**Issue by codingshot** [near-ndc/AstraPlusPlus#42]
## Feature Request
Ability to set quorum for each group

![Image](https://github.com/near-ndc/AstraPlusPlus/assets/45281667/88f42ee0-0723-422c-bd6f-726dbf01eb19)

**Comment by hippieontheblock** [comment]
https://near.org/astraplusplus.ndctools.near/widget/home?page=dao&tab=proposals&daoId=voting-body-v1.ndc-gwg.near&proposalId=10
