### ISSUE TITLE
Social feed must be redirected to social feed page in the url.

### ISSUE THREAD

**Issue by Eren-Yeaager** [near-ndc/AstraPlusPlus#90]
**Objective:**
When the user clicks on the Social feed page, its getting redirected to **"page=home"**(https://near.org/astraplusplus.ndctools.near/widget/home?page=home) , but it must be specified that the url is getting redirected to social feed page , something similar to **"page=social-feed"** 

**Screenshot:**

![Image](https://github.com/near-ndc/AstraPlusPlus/assets/91129111/a9d99437-ec33-46b9-b139-b988999a7b1a)

**Comment by Megha-Dev-19** [comment]
hey @Eren-Yeaager  I can update it but what will we show on home? 
we have to show some screen?
